### ISSUE TITLE
Issue with PlanetShine

### ISSUE THREAD

**Issue by Ippo343** [KSP-CKAN/CKAN-support#80] opened 2015-01-30 16:13 UTC
_From @autrilla on January 26, 2015 19:40_

Oh no! We tried to overwrite a file owned by another mod!
Please try a `ckan update` and try again.

If this problem re-occurs, then it maybe a packaging bug.
Please report it at:

https://github.com/KSP-CKAN/CKAN-meta/issues/new

Please including the following information in your report:

File           : GameData/PlanetShine/Config/CelestialBodies.cfg
Installing Mod : PlanetShine 0.2.2
Owning Mod     : AstronomersPack-PlanetShine
CKAN Version   : v1.5.6-0-g0000000 (beta)

_Copied from original issue: KSP-CKAN/CKAN-meta#283_

**Comment by Ippo343** [comment] 2015-01-30 16:13
_From @dbent on January 26, 2015 23:46_

```
Installing Mod : PlanetShine 0.2.2
Owning Mod : AstronomersPack-PlanetShine
```

You already have PlanetShine installed by virtue of installing `AstronomersPack-PlanetShine`.

**Comment by Ippo343** [comment] 2015-01-30 16:13
_From @autrilla on January 27, 2015 10:40_

@dbent That is just a configuration.

**Comment by Ippo343** [comment] 2015-01-30 16:13
_From @dbent on January 27, 2015 23:49_

@autrilla, `PlanetShine` is a dependency of `AstronomersPack-PlanetShine` was it not automatically installed when you installed `AstronomersPack-PlanetShine`?

**Comment by Dazpoet** [comment] 2015-05-02 01:24
unable to reproduce in any way I can think off, closing this.

**Closed by Dazpoet** 2015-05-02 01:24 UTC
