### ISSUE TITLE
CKAN lost track of one of my mods

### ISSUE THREAD

**Issue by Dazpoet** [KSP-CKAN/CKAN-support#68] opened 2015-01-23 22:06 UTC
A while ago I installed a mod called "SCANsat mission pack" and it appears to henceforth have been removed from CKAN.

This has created a situation where I am now unable to remove the mod through CKAN. It appears that the program recognizes this problem because it will also not let me remove SCANsat but instead throws me an exception when I try to remove it.

I have a hard time reproducing the error on a fresh install of CKAN due to the obvious problem of finding and installing a mod that no longer seems to exist in the repository.

The error I get is as follows:

************** Exception Text **************
CKAN.ModuleNotFoundKraken: Exception of type 'CKAN.ModuleNotFoundKraken' was thrown.
   at CKAN.Registry.LatestAvailable(String module, KSPVersion ksp_version)
   at CKAN.MainModList.<ComputeChangeSetFromModList>c__AnonStorey0.<>m__1(String rDep)
   at System.Linq.Enumerable.<>c__DisplayClass12`3.<CombineSelectors>b__11(TSource x)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.HashSet`1.UnionWith(IEnumerable`1 other)
   at CKAN.MainModList.ComputeChangeSetFromModList(Registry registry, KSP current_instance)
   at CKAN.Main.ModList_CellValueChanged(Object sender, DataGridViewCellEventArgs e)
   at System.Windows.Forms.DataGridViewCell.SetValue(Int32 rowIndex, Object value)
   at System.Windows.Forms.DataGridView.PushFormattedValue(DataGridViewCell& dataGridViewCurrentCell, Object formattedValue, Exception& exception)
   at System.Windows.Forms.DataGridView.CommitEdit(DataGridViewCell& dataGridViewCurrentCell, DataGridViewDataErrorContexts context, DataGridViewValidateCellInternal validateCell, Boolean fireCellLeave, Boolean fireCellEnter, Boolean fireRowLeave, Boolean fireRowEnter, Boolean fireLeave)
   at System.Windows.Forms.DataGridView.CommitEdit(DataGridViewDataErrorContexts context)
   at System.Windows.Forms.DataGridView.NotifyCurrentCellDirty(Boolean dirty)
   at System.Windows.Forms.DataGridViewCheckBoxCell.OnCommonContentClick(DataGridViewCellEventArgs e)
   at System.Windows.Forms.DataGridView.OnCellContentClick(DataGridViewCellEventArgs e)
   at System.Windows.Forms.DataGridViewCell.OnMouseUpInternal(DataGridViewCellMouseEventArgs e)
   at System.Windows.Forms.DataGridView.OnCellMouseUp(DataGridViewCellMouseEventArgs e)
   at System.Windows.Forms.DataGridView.OnMouseUp(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.DataGridView.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by Dazpoet** [comment] 2015-01-23 22:09
If it helps it appears the mod is placed under /GameData/CC_Contracts/SCANsat/

**Comment by hakan42** [comment] 2015-01-23 22:25
This one is caused by an overly aggressive removal on my part. 

Tomorrow, I will reinstate a "deprecated" version of this mod that should allow you removal. And actually document the way to handle "dead" addons. 

Note for the team: we solved the Universal Storage issue with an explicit "deprecated" version as well.

**Comment by Dazpoet** [comment] 2015-01-23 22:46
Perfect, looking forward to the fix and thanks for answering :)

**Comment by hakan42** [comment] 2015-01-23 22:53
@Dazpoet , just pushed the fix, I couldn't sleep :blush: 

Could you please "update" in the GUI and retry the upgrade and / or removal again?

**Comment by Dazpoet** [comment] 2015-01-23 23:06
Ah there it is, however the name is... interesting

The mod changed name to "z_DEPRECATED - Contract Pack: SCANSat Deprecated" which is quite a mouthfull. Right now I'm getting an exception again but it seems it might be on my end.

This is what I get:

System.IO.IOException: The process cannot access the file 'o:\steam\SteamApps\common\Kerbal Space Program\GameData\CC_Contracts\SCANsat' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound)
   at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
   at CKAN.ModuleInstaller.Uninstall(String modName)
   at CKAN.ModuleInstaller.UninstallList(IEnumerable`1 mods)
   at CKAN.Main.InstallMods(Object sender, DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)

I'll try rebooting the comp and see if that helps to exclude problems on my side.

**Comment by Dazpoet** [comment] 2015-01-23 23:10
Problem appears to have been on my side, a reboot solved the situation and I can now also remove SCANSat without being thrown errors :)

**Comment by hakan42** [comment] 2015-01-23 23:52
Yes, the name change was intentional so the (now deprecated) mod does not get shown in the middle of all others...

**Closed by hakan42** 2015-01-23 23:52 UTC
