### ISSUE TITLE
CKAN fails to build on Fedora 20 Linux

### ISSUE THREAD

**Issue by TNTftw21** [KSP-CKAN/CKAN-support#106] opened 2015-03-19 21:51 UTC
After seeing this neat little application for modding KSP, I decided that it would be worth not having to clutter my file system with a bunch of unorganized ZIP files.

However, CKAN fails to build. Going to CKAN-1.6.5/bin and executing `./ckan-build.py` gives me the following error:
```
NUnit version 2.4.8
   Copyright (C) 2002-2007 Charlie Poole.
   Copyright (C) 2002-2004 James W. Newkirk, Michael C. Two, Alexei A. Vorontsov.
   Copyright (C) 2000-2002 Philip Craig.
   All Rights Reserved.

   Runtime Environment - 
   OS Version: Unix 3.18.7.100
   CLR Version: 2.0.50727.1433 ( 2.10.8 (tarball Sat Aug  3 13:17:40 UTC 2013) )
  
   Unhandled Exception:
   System.TypeLoadException: Could not load type 'CKANTests.ModuleInstaller' from assembly  'Tests, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.

   Server stack trace: 
   at (wrapper managed-to-native) System.MonoType:GetMethodsByName (System.MonoType,string,System.Reflection.BindingFlags,bool,System.Type)
   at System.MonoType.GetMethods (BindingFlags bindingAttr) [0x00000] in /builddir/build/BUILD/mono-2.10.8/mcs/class/corlib/System/MonoType.cs:211 
   at NUnit.Core.Reflect.GetMethodWithAttribute (System.Type fixtureType, System.String attributeName, BindingFlags bindingFlags, Boolean inherit) [0x00000] in /builddir/build/BUILD/mono-2.10.8/mcs/nunit24/NUnitCore/core/Reflect.cs:212 
   at NUnit.Core.NUnitFramework.GetSetUpMethod (System.Type fixtureType) [0x00000] in /builddir/build/BUILD/mono-2.10.8/mcs/nunit24/NUnitCore/core/NUnitFramework.cs:103 
   at NUnit.Core.NUnitTestMethod..ctor (System.Reflection.MethodInfo method) [0x00000] in <filename unknown>:0 
   at NUnit.Core.Builders.NUnitTestCaseBuilder.MakeTestCase (System.Reflection.MethodInfo method) [0x00000] in /builddir/build/BUILD/mono-2.10.8/mcs/nunit24/NUnitCore/core/Builders/NUnitTestCaseBuilder.cs:59 
   at NUnit.Core.Builders.AbstractTestCaseBuilder.BuildFrom (System.Reflection.MethodInfo method) [0x00013] in /builddir/build/BUILD/mono-2.10.8/mcs/nunit24/NUnitCore/core/Builders/AbstractTestCaseBuilder.cs:79 
   at NUnit.Core.Extensibility.TestCaseBuilderCollection.BuildFrom (System.Reflection.MethodInfo method) [0x00029] in /builddir/build/BUILD/mono-2.10.8/mcs/nunit24/NUnitCore/core/Extensibility/TestCaseBuilderCollection.cs:53 
   at NUnit.Core.Builders.AbstractFixtureBuilder.BuildTestCase (System.Reflection.MethodInfo method) [0x00028] in /builddir/build/BUILD/mono-2.10.8/mcs/nunit24/NUnitCore/core/Builders/AbstractFixtureBuilder.cs:174 
   at NUnit.Core.Builders.AbstractFixtureBuilder.AddTestCases (System.Type fixtureType) [0x00020] in /builddir/build/BUILD/mono-2.10.8/mcs/nunit24/NUnitCore/core/Builders/AbstractFixtureBuilder.cs:144 
   at NUnit.Core.Builders.AbstractFixtureBuilder.BuildFrom (System.Type type) [0x0001a] in /builddir/build/BUILD/mono-2.10.8/mcs/nunit24/NUnitCore/core/Builders/AbstractFixtureBuilder.cs:73 
   at NUnit.Core.Extensibility.SuiteBuilderCollection.BuildFrom (System.Type type) [0x00029] in /builddir/build/BUILD/mono-2.10.8/mcs/nunit24/NUnitCore/core/Extensibility/SuiteBuilderCollection.cs:55 
   at NUnit.Core.TestFixtureBuilder.BuildFrom (System.Type type) [0x00000] in /builddir/build/BUILD/mono-2.10.8/mcs/nunit24/NUnitCore/core/TestFixtureBuilder.cs:31 
   at NUnit.Core.Builders.TestAssemblyBuilder.GetFixtures (System.Reflection.Assembly assembly, System.String ns) [0x00032] in /builddir/build/BUILD/mono-2.10.8/mcs/nunit24/NUnitCore/core/Builders/TestAssemblyBuilder.cs:189 
   at NUnit.Core.Builders.TestAssemblyBuilder.Build (System.String assemblyName, Boolean autoSuites) [0x0001a] in /builddir/build/BUILD/mono-2.10.8/mcs/nunit24/NUnitCore/core/Builders/TestAssemblyBuilder.cs:99 
   at NUnit.Core.Builders.TestAssemblyBuilder.Build (System.String assemblyName, System.String testName, Boolean autoSuites) [0x00016] in /builddir/build/BUILD/mono-2.10.8/mcs/nunit24/NUnitCore/core/Builders/TestAssemblyBuilder.cs:76 
   at NUnit.Core.TestSuiteBuilder.BuildSingleAssembly (NUnit.Core.TestPackage package) [0x0001e] in /builddir/build/BUILD/mono-2.10.8/mcs/nunit24/NUnitCore/core/TestSuiteBuilder.cs:119 
   at NUnit.Core.TestSuiteBuilder.Build (NUnit.Core.TestPackage package) [0x00025] in /builddir/build/BUILD/mono-2.10.8/mcs/nunit24/NUnitCore/core/TestSuiteBuilder.cs:65 
   at NUnit.Core.SimpleTestRunner.Load (NUnit.Core.TestPackage package) [0x0000b] in /builddir/build/BUILD/mono-2.10.8/mcs/nunit24/NUnitCore/core/SimpleTestRunner.cs:107 
   at NUnit.Core.ProxyTestRunner.Load (NUnit.Core.TestPackage package) [0x00000] in /builddir/build/BUILD/mono-2.10.8/mcs/nunit24/NUnitCore/core/ProxyTestRunner.cs:104 
   at NUnit.Core.ProxyTestRunner.Load (NUnit.Core.TestPackage package) [0x00000] in /builddir/build/BUILD/mono-2.10.8/mcs/nunit24/NUnitCore/core/ProxyTestRunner.cs:104 
   at NUnit.Core.RemoteTestRunner.Load (NUnit.Core.TestPackage package) [0x0005b] in /builddir/build/BUILD/mono-2.10.8/mcs/nunit24/NUnitCore/core/RemoteTestRunner.cs:45 
   at (wrapper xdomain-dispatch) NUnit.Core.RemoteTestRunner:Load (object,byte[]&,byte[]&)

   Exception rethrown at [0]: 

    at (wrapper xdomain-invoke) NUnit.Core.RemoteTestRunner:Load (NUnit.Core.TestPackage)
    at NUnit.Util.TestDomain.Load (NUnit.Core.TestPackage package) [0x0003f] in /builddir/build/BUILD/mono-2.10.8/mcs/nunit24/ClientUtilities/util/TestDomain.cs:57
```
I have been told that I should be able to find a more recent version of NUnit in CKAN-core/packages, but it doesn't have an executable, among other things. I have no idea what is wrong with the build. Any help is appreciated, and I am willing to provide any information necessary. My OS is Fedora 20 Linux running Kernel version 3.18.7-100.fc20.x86_64.

**Comment by TNTftw21** [comment] 2015-03-20 01:22
Also, after trying to manually install NUnit 2.6.4, I found that `xbuild` was giving this output:

+ xbuild /verbosity:minimal CKAN-core.sln
XBuild Engine Version 2.10.8.0
Mono, Version 2.10.8.0
Copyright (C) Marek Sieradzki 2005-2008, Novell 2008-2011.
                Configuration: Debug Platform: AnyCPU
                Created directory "bin/Debug/"
                Created directory "obj/Debug/"
/usr/lib/mono/4.0/Microsoft.Common.targets:  warning : Found a conflict between : 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' and 'mscorlib, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. Using 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' reference.                                                                                                                                
/usr/lib/mono/4.0/Microsoft.Common.targets:  warning : Found a conflict between : 'System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' and 'System, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. Using 'System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' reference.                                                                                                                                      
/usr/lib/mono/4.0/Microsoft.Common.targets:  warning : Found a conflict between : 'System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' and 'System.Xml, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. Using 'System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' reference.                                                                                                                          
/usr/lib/mono/4.0/Microsoft.Common.targets:  warning : Found a conflict between : 'System.Transactions, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' and 'System.Transactions, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. Using 'System.Transactions, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' reference.                                                                                               
Registry/Registry.cs(31,41): warning CS0169: The private field `CKAN.Registry.unsortedRepositories' is never used
FileIdentifier.cs(10,38): warning CS0414: The private field `CKAN.FileIdentifier.log' is assigned but its value is never used
Configuration: Debug Platform: AnyCPU
Created directory "bin/Debug/"
Created directory "obj/Debug/"
/usr/lib/mono/4.0/Microsoft.Common.targets:  warning : Found a conflict between : 'System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' and 'System, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. Using 'System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' reference.                                                                                                                                      
/usr/lib/mono/4.0/Microsoft.Common.targets:  warning : Found a conflict between : 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' and 'mscorlib, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. Using 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' reference.                                                                                                                                
/usr/lib/mono/4.0/Microsoft.Common.targets:  warning : Found a conflict between : 'System.Transactions, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' and 'System.Transactions, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. Using 'System.Transactions, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' reference.

I have no idea if this is any help at all.

**Comment by mgsdk** [comment] 2015-03-21 18:59
I have the same issue when using the build script, but not when working with CKAN in MonoDevelop. After looking a bit around it would seem the issue is related to the framework target of nunit. The default shortcut of nunit-console on my system (Arch Linux) invokes the same version as you have, however using nunit-console4 solves the issue, as this targets the same framework version as CKAN.

If you have access to nunit-console4 (Or a version of nunit targeting framework version 4.0) you could try to edit the build.sh scripts in CKAN-core and CKAN-GUI to invoke that version instead of nunit-console. Then you would manually have to run the build.sh script in each subfolder. Start with core, then GUI and finally cmdline.

**Comment by TNTftw21** [comment] 2015-03-21 19:27
YUM doesn't appear to have any packages containing `nunit-console4`. The latest version available to YUM is 2.10.8, and the newest RPM I can find is a 3.8.0 on SourceForge.

**Comment by TNTftw21** [comment] 2015-03-21 19:44
I found out that 3.8.0 provides `nunit-console4`, but it still references the 2.4.8 version of the command.

**Comment by pjf** [comment] 2015-04-12 01:06
Just a quick note to say that mgsdk's awesome work on this has been merged. :)

**Comment by TNTftw21** [comment] 2015-04-12 19:21
Thanks, that got me past this issue, but right into another issue:

```
+ nunit-console --exclude=FlakyNetwork Tests/bin/Debug/Tests.dll
NUnit version 2.4.8
Copyright (C) 2002-2007 Charlie Poole.
Copyright (C) 2002-2004 James W. Newkirk, Michael C. Two, Alexei A. Vorontsov.
Copyright (C) 2000-2002 Philip Craig.
All Rights Reserved.

Runtime Environment - 
   OS Version: Unix 3.18.9.100
  CLR Version: 2.0.50727.1433 ( 2.10.8 (tarball Sat Aug  3 13:17:40 UTC 2013) )

Excluded categories: FlakyNetwork
Missing method .ctor in assembly /tmp/nunit20/ShadowCopyCache/30785_635644450880130390/Tests/assembly/shadow/eb593da3/1a0a338c_f1530e2f_00000001/log4net.dll, type System.Security.SecurityRulesAttribute
Can't find custom attr constructor image: /tmp/nunit20/ShadowCopyCache/30785_635644450880130390/Tests/assembly/shadow/eb593da3/1a0a338c_f1530e2f_00000001/log4net.dll mtoken: 0x0a000026
.FMissing method System.Threading.Monitor::Enter(object,bool&) in assembly /usr/lib/mono/2.0/mscorlib.dll, referenced in assembly /tmp/nunit20/ShadowCopyCache/30785_635644450880130390/Tests/assembly/shadow/eb593da3/1a0a338c_f1530e2f_00000001/log4net.dll
.F.F.F.F.F.F.F
Tests run: 8, Failures: 8, Not run: 0, Time: 0.153 seconds

Test Case Failures:
1) Tests.GUI.GUIModTests.HasUpdateReturnsTrueWhenUpdateAvailible : System.TypeLoadException : A type load exception has occurred.
at Tests.GUI.GUIModTests.HasUpdateReturnsTrueWhenUpdateAvailible () [0x00000] in /home/tony/GitHub/CKAN/bin/CKAN-GUI/Tests/GUI/GUIMod.cs:28
at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x000d0] in /builddir/build/BUILD/mono-2.10.8/mcs/class/corlib/System.Reflection/MonoMethod.cs:226

2) Tests.GUI.GUIModTests.NewGuiModsAreNotSelectedForUpgrade : System.TypeLoadException : A type load exception has occurred.
at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x000d0] in /builddir/build/BUILD/mono-2.10.8/mcs/class/corlib/System.Reflection/MonoMethod.cs:226

3) Tests.GUI.MainModListTests.ComputeChangeSetFromModList_WithEmptyList_HasEmptyChangeSet : System.TypeLoadException : A type load exception has occurred.
at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x000d0] in /builddir/build/BUILD/mono-2.10.8/mcs/class/corlib/System.Reflection/MonoMethod.cs:226

4) Tests.GUI.MainModListTests.CountModsByFilter_EmptyModList_ReturnsZeroForAllFilters : System.TypeLoadException : A type load exception has occurred.
at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x000d0] in /builddir/build/BUILD/mono-2.10.8/mcs/class/corlib/System.Reflection/MonoMethod.cs:226

5) Tests.GUI.MainModListTests.IsVisible_WithAllAndNoNameFilter_ReturnsTrueForCompatible : System.TypeLoadException : A type load exception has occurred.
at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x000d0] in /builddir/build/BUILD/mono-2.10.8/mcs/class/corlib/System.Reflection/MonoMethod.cs:226

6) Tests.GUI.MainModListTests.OnCreation_HasDefaultFilters : System.TypeLoadException : A type load exception has occurred.
at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x000d0] in /builddir/build/BUILD/mono-2.10.8/mcs/class/corlib/System.Reflection/MonoMethod.cs:226

7) Tests.GUI.MainModListTests.OnModTextFilterChanges_CallsEventHandler : System.TypeLoadException : A type load exception has occurred.
at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x000d0] in /builddir/build/BUILD/mono-2.10.8/mcs/class/corlib/System.Reflection/MonoMethod.cs:226

8) Tests.GUI.MainModListTests.OnModTypeFilterChanges_CallsEventHandler : System.TypeLoadException : A type load exception has occurred.
at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x000d0] in /builddir/build/BUILD/mono-2.10.8/mcs/class/corlib/System.Reflection/MonoMethod.cs:226
```
I have no honest idea what this means, but I assume that the test suite is failing somewhere. If it's not one problem, it's another, right?

**Comment by TNTftw21** [comment] 2015-04-22 01:52
After pulling the latest 2-line change for CKAN, the build runs well (skipping the tests do to lack of nunit-console4). However, now CKAN fails at runtime with this error:
```console
1399 [1] ERROR CKAN.ErrorDialog (null) - Unhandled exception:
System.Exception: Unexpected number of bits: 0
  at System.Drawing.Icon.BuildBitmapOnWin32 () [0x00000] in <filename unknown>:0 
  at System.Drawing.Icon.GetInternalBitmap () [0x00000] in <filename unknown>:0 
  at System.Drawing.Icon.ToBitmap () [0x00000] in <filename unknown>:0 
  at System.Drawing.Icon.get_Handle () [0x00000] in <filename unknown>:0 
  at (wrapper remoting-invoke-with-check) System.Drawing.Icon:get_Handle ()
  at System.Windows.Forms.XplatUIWin32.SetIcon (IntPtr hwnd, System.Drawing.Icon icon) [0x00000] in <filename unknown>:0 
  at System.Windows.Forms.XplatUI.SetIcon (IntPtr handle, System.Drawing.Icon icon) [0x00000] in <filename unknown>:0 
  at System.Windows.Forms.Form.CreateHandle () [0x00000] in <filename unknown>:0 
  at System.Windows.Forms.Control.CreateControl () [0x00000] in <filename unknown>:0 
  at System.Windows.Forms.Control.SetVisibleCore (Boolean value) [0x00000] in <filename unknown>:0 
  at System.Windows.Forms.Form.SetVisibleCore (Boolean value) [0x00000] in <filename unknown>:0 
  at System.Windows.Forms.Control.set_Visible (Boolean value) [0x00000] in <filename unknown>:0 
  at (wrapper remoting-invoke-with-check) System.Windows.Forms.Control:set_Visible (bool)
  at System.Windows.Forms.Application.RunLoop (Boolean Modal, System.Windows.Forms.ApplicationContext context) [0x00000] in <filename unknown>:0 
  at System.Windows.Forms.Application.Run (System.Windows.Forms.ApplicationContext context) [0x00000] in <filename unknown>:0 
  at System.Windows.Forms.Application.Run (System.Windows.Forms.Form mainForm) [0x00000] in <filename unknown>:0 
  at CKAN.Main..ctor (System.String[] cmdlineArgs, CKAN.GUIUser User, Boolean showConsole) [0x00000] in <filename unknown>:0 
  at (wrapper remoting-invoke-with-check) CKAN.Main:.ctor (string[],CKAN.GUIUser,bool)
  at CKAN.GUI.Main_ (System.String[] args, Boolean showConsole) [0x00000] in <filename unknown>:0 
  at CKAN.CmdLine.MainClass.Gui (CKAN.CmdLine.GuiOptions options, System.String[] args) [0x00000] in <filename unknown>:0 
  at CKAN.CmdLine.MainClass.Main (System.String[] args) [0x00000] in <filename unknown>:0  
Stacktrace:

  at <unknown> <0xffffffff>
  at (wrapper managed-to-native) object.__icall_wrapper_mono_debugger_agent_user_break () <0xffffffff>
  at CKAN.GUI.UnhandledExceptionEventHandler (object,System.UnhandledExceptionEventArgs) <0x00083>
  at (wrapper runtime-invoke) <Module>.runtime_invoke_void__this___object_object (object,intptr,intptr,intptr) <0xffffffff>
```
It also says something about getting a SIG_SEGV, so I'm thinking it has to do with the lack of mono 4.

**Closed** 2015-05-21 06:07 UTC
