### ISSUE TITLE
conflicts

### ISSUE THREAD

**Issue by Bit-Fiddler** [KSP-CKAN/CKAN-support#145] opened 2015-05-16 01:38 UTC
JSI part utilities is conflicting with RPM
and KAX is conflicting with Firespitter

**Comment by mgsdk** [comment] 2015-05-16 06:35
Looking into a solution to the first one. The second issue is a duplicate of https://github.com/KSP-CKAN/CKAN-meta/issues/472 I believe.

**Comment by Bit-Fiddler** [comment] 2015-05-17 04:13
JSI and RPM get along fine now, but still having issues with KAX and FS.   Am I doing something wrong?  as the post there seems to say it should be fine?

**Comment by Dazpoet** [comment] 2015-05-17 23:01
KAX and FS have not been resolved yet afaik, we're looking into it still.

**Closed** 2015-05-21 06:16 UTC
