### ISSUE TITLE
Dev repository doesn't supply latest version, intended?

### ISSUE THREAD

**Issue by Dazpoet** [KSP-CKAN/CKAN-support#78] opened 2015-01-29 21:53 UTC
So SCANsat (because it is always SCANsat) came out with the 10.0 version today and ofcourse I wanted to upgrade ASAP because "yay new version!".

I've been using the dev build up until now and when 10.0 came around I couldn't upgrade to it and instead had to revert to uninstalling the dev version (including the contract pack depending on it) to be able to install the newer version.

Trying to install 10.0 before removing the dev release threw me an InconsistentKraken which I wasn't smart enough to save a copy off. It said something like scansat and scansat-dev same thing but not same thing and didn't seem to like it very much.

My expectation of adding a dev repo was that I would always have the bleeding edge releases independant of them being currently classed as Stable, RC or something else. This seems to not be the case, will I need to switch my stable to dev repo again when a new non-stable version comes out? If so I guess a dev repo for something that more things depend on (say ModuleManager) might make CKAN very unhappy.

**Comment by hakan42** [comment] 2015-01-29 22:06
Honestly, we did not have the opportunity to verify a dev - > non-dev transfer until now. 

I have to rethink the way I have set up the dev repos.

**Comment by hakan42** [comment] 2015-02-16 14:00
The SCANsat-dev repo should provide both the stable and the prerelease versions now. Whether everything works as intended will be seen whenever SCANsat creates a 11.x prerelease :smiling_imp: 

Also, it will be interesting to see whether our version comparision system (which is alphabetical as of now) can properly handle the upgrade from v9.x.y to v10.0 :confused:

**Closed by hakan42** 2015-02-16 14:00 UTC
