### ISSUE TITLE
Error installing TAC-LS

### ISSUE THREAD

**Issue by Ippo343** [KSP-CKAN/CKAN-support#79] opened 2015-01-30 16:12 UTC
_From @reseune on January 28, 2015 1:52_

The following error is received when installing TAC-LS with TAC-LS Stock Config, or when attempting to install TAC-LS Stock Config by itself.  

Module "TAC Life Support (TACLS) - stock config" successfully installed
Oh no! We tried to overwrite a file owned by another mod!
Please try a `ckan update` and try again.
If this problem re-occurs, then it maybe a packaging bug.
Please report it at:
https://github.com/KSP-CKAN/CKAN-meta/issues/new
Please including the following information in your report:
File           : GameData/ThunderAerospace/TacLifeSupportContainers/Food.cfg
Installing Mod : TACLS v0.10.2b
Owning Mod     : TACLS-Config-Stock
CKAN Version   : v1.5.3-0-g0000000 (beta)
Your GameData has been returned to its original state.
Error!

_Copied from original issue: KSP-CKAN/CKAN-meta#286_

**Comment by Dazpoet** [comment] 2015-03-14 13:01
I am unable to reproduce this problem on a clean install of KSP 0.90 using CKAN 1.6.5. Seems to work fine from both cmdline and GUI.

From what I can see no changes have been made to the .netkan files in quite some time though so I'm unsure why it didn't work for @reseune

**Comment by reseune** [comment] 2015-03-14 13:06
I can confirm that the issue is resolved in the latest version of CKAN (1.6.5).  FWIW, I can still reproduce the problem in the earlier version, but it's all moot now... and thank you. :+1:

**Closed** 2015-03-15 10:43 UTC
